.idea/misc.xml, README.md, analyticsexample/build.gradle, analyticsexample/src/main/java/com/bitmovin/exoplayeranalyticsexample/MainActivity.java, bitmovinanalyticsexample/build.gradle, collector/build.gradle, collector/src/main/java/com/bitmovin/analytics/analytics/BitmovinAnalytics.java
updated to exo 2.7.3 and bitmovin sdk 2.9.0
added 1 as the player startup time
=> Android Collector 1.2.0

.idea/misc.xml, README.md, analyticsexample/build.gradle, analyticsexample/src/main/java/com/bitmovin/exoplayeranalyticsexample/MainActivity.java, bitmovinanalyticsexample/build.gradle, collector/build.gradle, collector/src/main/java/com/bitmovin/analytics/analytics/BitmovinAnalytics.java
Upgraded to Exoplayer 2.7.3
Upgraded to Bitmovin SDK 2.9.0
Added a default player startup time to “1”
=> Release 1.2.0

README.md, analyticsexample/build.gradle, analyticsexample/src/main/java/com/bitmovin/exoplayeranalyticsexample/MainActivity.java, bitmovinanalyticsexample/build.gradle, bitmovinanalyticsexample/src/main/java/com/bitmovin/bitmovinanalyticsexample/MainActivity.java, collector/build.gradle, collector/src/main/java/com/bitmovin/analytics/adapters/BitmovinSdkAdapter.java, collector/src/main/java/com/bitmovin/analytics/adapters/ExoPlayerAdapter.java, collector/src/main/java/com/bitmovin/analytics/analytics/BitmovinAnalytics.java
- Upgraded to ExoPlayer 2.8.1 and Bitmovin SDK 2.10.2
- Switched to using OnVideoPlaybackQualityChanged instead of OnVideoQualityChanged. This allows us to track all quality change events
=> Release 1.3.3

README.md, analyticsexample/build.gradle, bitmovinanalyticsexample/build.gradle, collector/build.gradle
- upgraded Bitmovin Player to 2.10.3
=> Release 1.3.5 

README.md, analyticsexample/build.gradle, bitmovinanalyticsexample/build.gradle, collector/build.gradle
- upgrade to Bitmovin SDK 2.12.0
=> Release 1.3.7

CHANGELOG.md, collector-bitmovin-player/src/main/java/com/bitmovin/analytics/bitmovin/player/BitmovinSdkAdapter.java, collector/src/main/java/com/bitmovin/analytics/utils/Util.java
- Issue(s): https://github.com/bitmovin/analytics-issues/issues/601
- Description: Added `progressive` and `smooth` to available stream formats and made sure that the right source is reported from the player.
=> Handling sources correctly

CHANGELOG.md, README.md, analyticsexample/build.gradle, bitmovinanalyticsexample/build.gradle, collector-bitmovin-player/build.gradle, collector-exoplayer/build.gradle, collector/build.gradle
- Description: Bumped to v1.6.2
=> Bumped version

CHANGELOG.md, collector-bitmovin-player/src/main/java/com/bitmovin/analytics/bitmovin/player/BitmovinSdkAdapter.java
- Fixes: 
- Description: Change PlayerState to PAUSE in onPausedListener
=> Change PlayerState in onPaused handler

CHANGELOG.md, collector-bitmovin-player/src/main/java/com/bitmovin/analytics/bitmovin/player/BitmovinSdkAdapter.java, collector/src/androidTest/java/com/bitmovin/analytics/data/EventDataTest.java, collector/src/main/java/com/bitmovin/analytics/BitmovinAnalytics.java, collector/src/main/java/com/bitmovin/analytics/data/EventData.java, collector/src/main/java/com/bitmovin/analytics/data/EventData.kt, collector/src/main/java/com/bitmovin/analytics/data/HttpBackend.java, collector/src/main/java/com/bitmovin/analytics/data/LanguageInformation.kt, collector/src/main/java/com/bitmovin/analytics/data/LegacyEventData.java, collector/src/main/java/com/bitmovin/analytics/stateMachines/PlayerState.java, collector/src/main/java/com/bitmovin/analytics/stateMachines/StateMachineListener.java
- Fixes: https://bitmovin.atlassian.net/browse/AN-725, https://bitmovin.atlassian.net/browse/AN-828
- Description: Watch for events of changing subtitles or audio track and track them in the event data. Also send a boolean, indicating if any subtitle is enabled.
=> AN-828 Add audio and subtitle tracking

CHANGELOG.md, README.md, build.gradle, collector-bitmovin-player/build.gradle
- Fixes: 
- Description: Bump version v1.10.0
=> Bump version v1.10.0

CHANGELOG.md, README.md, build.gradle
=> bump version v1.11.0

CHANGELOG.md, README.md, build.gradle
=> bump v1.11.1

CHANGELOG.md, README.md, build.gradle
=> bump v1.11.2

CHANGELOG.md, README.md, build.gradle
=> bump version 1.11.3

CHANGELOG.md, analyticsexample/src/main/java/com/bitmovin/exoplayeranalyticsexample/MainActivity.java, bitmovinanalyticsexample/src/main/java/com/bitmovin/bitmovinanalyticsexample/MainActivity.java, build.gradle, collector-bitmovin-player/src/main/java/com/bitmovin/analytics/bitmovin/player/BitmovinSdkAdapter.java, collector-exoplayer/src/main/java/com/bitmovin/analytics/exoplayer/ExoPlayerAdapter.java, collector/src/main/java/com/bitmovin/analytics/BitmovinAnalytics.java, collector/src/main/java/com/bitmovin/analytics/adapters/PlayerAdapter.java, collector/src/main/java/com/bitmovin/analytics/data/DRMInformation.kt, collector/src/main/java/com/bitmovin/analytics/data/EventData.kt, collector/src/main/java/com/bitmovin/analytics/enums/DRMType.kt
- Fixes: https://bitmovin.atlassian.net/browse/AN-1170
- Description: add drm metrics to exoPlayer and Bitmovin Player
=> AN-1170 add drm metrics to exoPlayer and Bitmovin Player

CHANGELOG.md, build.gradle
=> bump version 1.12.0

CHANGELOG.md, collector/src/main/java/com/bitmovin/analytics/stateMachines/PlayerState.java, collector/src/main/java/com/bitmovin/analytics/stateMachines/PlayerStateMachine.java
- Fixes: https://bitmovin.atlassian.net/browse/AN-1281
- Description:
=> AN-1281 added heartbeat during rebuffering state

CHANGELOG.md, analyticsexample/src/main/res/values/strings.xml, collector-exoplayer/src/main/java/com/bitmovin/analytics/exoplayer/ExoPlayerAdapter.java
- Fixes: https://bitmovin.atlassian.net/browse/AN-1410
- Description: no rebuffer state allowed after seeking
=> AN-1410 seek-buffer transition fix

CHANGELOG.md, README.md, build.gradle
=> bump version to 1.13.0

CHANGELOG.md, analyticsexample/build.gradle, analyticsexample/src/main/java/com/bitmovin/exoplayeranalyticsexample/MainActivity.java, analyticsexample/src/main/res/layout/activity_main.xml, bitmovinanalyticsexample/build.gradle, bitmovinanalyticsexample/src/main/java/com/bitmovin/bitmovinanalyticsexample/MainActivity.java, bitmovinanalyticsexample/src/main/res/layout/activity_main.xml, build.gradle, collector-bitmovin-player/build.gradle, collector-exoplayer/build.gradle, collector/build.gradle, collector/src/test/java/com/bitmovin/analytics/BitmovinAnalyticsTest.kt, collector/src/test/java/com/bitmovin/analytics/EventDataFactoryTest.kt, gradle.properties
- Fixes: https://bitmovin.atlassian.net/browse/AN-1394
- Description: migration to androidX
- please try to checkout this branch and try to build/run the project
=> AN-1394 android x migration

CHANGELOG.md, collector-bitmovin-player/src/main/java/com/bitmovin/analytics/bitmovin/player/BitmovinSdkAdapter.java, collector-exoplayer/src/main/java/com/bitmovin/analytics/exoplayer/ExoPlayerAdapter.java, collector/src/main/java/com/bitmovin/analytics/BitmovinAnalytics.java, collector/src/main/java/com/bitmovin/analytics/adapters/PlayerAdapter.java
- Fixes: https://bitmovin.atlassian.net/browse/AN-1439
- Description: Reset download speed metric after every sample sent
=> AN-1439 Reset download speed metric after every sample sent

collector/src/main/java/com/bitmovin/analytics/utils/DownloadSpeedMeter.kt
- Fixes: /
- Description: Changed download speed threshold to bytes per millisecond
=> Changed download speed threshold to bytes per millisecond

CHANGELOG.md, README.md, build.gradle
=> bump version 1.14.0

build.gradle, codeship-services.yml, codeship-steps.yml, collector-bitmovin-player/build.gradle, collector-exoplayer/build.gradle, collector/build.gradle, collector/src/main/java/com/bitmovin/analytics/data/DebuggingEventDataDispatcher.kt, collector/src/main/java/com/bitmovin/analytics/data/EventData.kt, collector/src/main/java/com/bitmovin/analytics/data/SpeedMeasurement.kt
- Fixes: https://bitmovin.atlassian.net/browse/AN-1427
- Description:
=> AN-1427 added codeship configs

CHANGELOG.md, README.md, build.gradle
=> bump version to v1.15.0

CHANGELOG.md, collector-exoplayer/src/main/java/com/bitmovin/analytics/exoplayer/ExoPlayerExceptionMapper.kt, collector/src/main/java/com/bitmovin/analytics/data/ErrorCode.kt
- Fixes: https://bitmovin.atlassian.net/browse/AN-1507
- Description: added BehindLiveWindowError to ExceptionMapper
- added general information of Source errors if unknown source error
=> AN-1507 added BehindLiveWindowError to ExceptionMapper

CHANGELOG.md, README.md, build.gradle
=> bump version to 1.16.0

CHANGELOG.md, README.md, build.gradle
=> bump version

CHANGELOG.md, collector-bitmovin-player/src/main/java/com/bitmovin/analytics/bitmovin/player/BitmovinSdkAdapter.java, collector-exoplayer/src/main/java/com/bitmovin/analytics/exoplayer/ExoPlayerAdapter.java, collector-exoplayer/src/test/java/com/bitmovin/analytics/exoplayer/ExoPlayerAdapterTest.kt, collector/src/main/java/com/bitmovin/analytics/CollectorConfig.java, collector/src/main/java/com/bitmovin/analytics/enums/AnalyticsErrorCodes.kt, collector/src/main/java/com/bitmovin/analytics/stateMachines/PlayerState.java, collector/src/main/java/com/bitmovin/analytics/stateMachines/PlayerStateMachine.java, collector/src/main/java/com/bitmovin/analytics/utils/Util.java
- Fixes: https://bitmovin.atlassian.net/browse/AN-1560
- Description: Added counter for tracking number of quality changes and timer for resetting counter
=> AN-1560 restrict quality changes

CHANGELOG.md, README.md, build.gradle
- Fixes: /
- Description: Bump version
=> Bump version v1.18.0

publish.sh
=> AN-1698 Added api notification

CHANGELOG.md, README.md, build.gradle
=> Bumped version to 1.19.0

publish.sh
=> Fixed typo in git push

codeship-services.yml, codeship-steps.yml
- Fixes: https://bitmovin.atlassian.net/browse/DEVOPS-1868
- Description: We do no longer use Codeship.
=> cleanup codeship leftovers
